version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./.env.example
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev -- --host
